# Generated by Django 3.2.4 on 2021-07-08 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='region',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
