# Generated by Django 3.2.4 on 2021-07-08 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_profile_region'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
