# Generated by Django 3.2.4 on 2021-07-06 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['id']},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='blog',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='comment_contents',
            new_name='comment_body',
        ),
    ]
